"""Remove ScheduleException table

Revision ID: 67c4f22a0032
Revises: 810f1a9e9c79
Create Date: 2026-01-07 18:21:52.037241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67c4f22a0032'
down_revision: Union[str, Sequence[str], None] = '810f1a9e9c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_exception')
    op.add_column('class_session', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.add_column('class_session', sa.Column('rescheduled_from_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'class_session_rescheduled_from_id_fkey',
        'class_session',
        'class_session',
        ['rescheduled_from_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'class_session_rescheduled_from_id_fkey',
        'class_session',
        type_='foreignkey',
    )
    op.drop_column('class_session', 'rescheduled_from_id')
    op.drop_column('class_session', 'cancellation_reason')
    op.create_table('schedule_exception',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('class_group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('exception_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_group.id'], name=op.f('schedule_exception_class_group_id_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('schedule_exception_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('schedule_exception_pkey'))
    )
    # ### end Alembic commands ###
