"""Add role column to users table

Revision ID: 81c0a31fd8c4
Revises: d7a07c78982e
Create Date: 2025-12-30 16:21:50.674067

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81c0a31fd8c4"
down_revision: Union[str, Sequence[str], None] = "d7a07c78982e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("role", sa.String(length=32), nullable=True)
    )
    op.execute("UPDATE \"user\" SET role = 'student'")
    op.alter_column("user", "role", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role")
    # ### end Alembic commands ###
