"""Add attendance, payments and other tables

Revision ID: 8462a38d6702
Revises: 67c4f22a0032
Create Date: 2026-01-07 20:08:23.283485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

package_type = postgresql.ENUM(
    "SEMESTER",
    "MONTHLY",
    "SINGLE_ENTRY",
    "MULTI_ENTRY",
    name="package_type",
    create_type=False,
)
charge_type = postgresql.ENUM(
    "MONTHLY_FEE",
    "ADDITIONAL_CLASSES",
    "ADJUSTMENT",
    name="charge_type",
    create_type=False,
)
charge_status = postgresql.ENUM(
    "OPEN",
    "PAID",
    "PARTIAL",
    "CANCELLED",
    name="charge_status",
    create_type=False,
)
notification_type = postgresql.ENUM(
    "PAYMENT_OVERDUE",
    "ENROLL_CONFIRM",
    name="notification_type",
    create_type=False,
)
notification_status = postgresql.ENUM(
    "PENDING",
    "SENT",
    "FAILED",
    name="notification_status",
    create_type=False,
)
payment_method = postgresql.ENUM(
    "CASH",
    "TRANSFER",
    "CARD",
    name="payment_method",
    create_type=False,
)
request_type = postgresql.ENUM(
    "ACCOUNT_DELETION",
    "GROUP_TRANSFER",
    "ROOM_RENTAL",
    name="request_type",
    create_type=False,
)
request_status = postgresql.ENUM(
    "PENDING",
    "APPROVED",
    "REJECTED",
    "CANCELLED",
    name="request_status",
    create_type=False,
)
room_booking_status = postgresql.ENUM(
    "PENDING",
    "APPROVED",
    "REJECTED",
    "COMPLETED",
    "CANCELLED",
    name="room_booking_status",
    create_type=False,
)
enrollment_status = postgresql.ENUM(
    "ACTIVE",
    "CANCELLED",
    "WAITLISTED",
    "MOVED",
    "COMPLETED",
    name="enrollment_status",
    create_type=False,
)
attendance_status = postgresql.ENUM(
    "PRESENT",
    "ABSENT",
    "EXCUSED",
    name="attendance_status",
    create_type=False,
)
user_package_status = postgresql.ENUM(
    "ACTIVE",
    "EXPIRED",
    "USED",
    name="user_package_status",
    create_type=False,
)

# revision identifiers, used by Alembic.
revision: str = '8462a38d6702'
down_revision: Union[str, Sequence[str], None] = '67c4f22a0032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    package_type.create(bind, checkfirst=True)
    charge_type.create(bind, checkfirst=True)
    charge_status.create(bind, checkfirst=True)
    notification_type.create(bind, checkfirst=True)
    notification_status.create(bind, checkfirst=True)
    payment_method.create(bind, checkfirst=True)
    request_type.create(bind, checkfirst=True)
    request_status.create(bind, checkfirst=True)
    room_booking_status.create(bind, checkfirst=True)
    enrollment_status.create(bind, checkfirst=True)
    attendance_status.create(bind, checkfirst=True)
    user_package_status.create(bind, checkfirst=True)
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('package_type', package_type, nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('number_of_classes', sa.Integer(), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', charge_type, nullable=False),
    sa.Column('status', charge_status, nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', notification_type, nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('email_to', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', notification_status, nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_method', payment_method, nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', request_type, nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('status', request_status, nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision_by', sa.UUID(), nullable=True),
    sa.Column('decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['decision_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_rental_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', room_booking_status, nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_allocation',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('charge_id', sa.Integer(), nullable=False),
    sa.Column('amount_allocated', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['charge_id'], ['charge.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.PrimaryKeyConstraint('payment_id', 'charge_id'),
    sa.UniqueConstraint('payment_id', 'charge_id', name='uq_payment_allocation_payment_charge')
    )
    op.create_table('enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('class_group_id', sa.Integer(), nullable=False),
    sa.Column('status', enrollment_status, nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_group.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'class_group_id', name='uq_enrollment_student_class_group')
    )
    op.create_index('ix_enrollment_class_group_status', 'enrollment', ['class_group_id', 'status'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', attendance_status, nullable=False),
    sa.Column('marked_by', sa.UUID(), nullable=True),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_makeup', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_session.id'], ),
    sa.ForeignKeyConstraint(['marked_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_session_id', 'student_id', name='uq_attendance_session_student')
    )
    op.create_table('user_package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('activation_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('classes_remaining', sa.Integer(), nullable=False),
    sa.Column('status', user_package_status, nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollment.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_package')
    op.drop_table('attendance')
    op.drop_index('ix_enrollment_class_group_status', table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_table('payment_allocation')
    op.drop_table('room_rental_booking')
    op.drop_table('request')
    op.drop_table('payment')
    op.drop_table('notification')
    op.drop_table('charge')
    op.drop_table('package')
    bind = op.get_bind()
    user_package_status.drop(bind, checkfirst=True)
    attendance_status.drop(bind, checkfirst=True)
    enrollment_status.drop(bind, checkfirst=True)
    room_booking_status.drop(bind, checkfirst=True)
    request_status.drop(bind, checkfirst=True)
    request_type.drop(bind, checkfirst=True)
    payment_method.drop(bind, checkfirst=True)
    notification_status.drop(bind, checkfirst=True)
    notification_type.drop(bind, checkfirst=True)
    charge_status.drop(bind, checkfirst=True)
    charge_type.drop(bind, checkfirst=True)
    package_type.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
